export default {
    CHANGE: "CHANGE",
    TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR",
    LIST_CODES: "LIST_CODES",
    LIST_PLACES: "LIST_PLACES",
    LIST_TOURS: "LIST_TOURS",
    LIST_TRIPS: "LIST_TRIPS",
    LIST_TICKETS: "LIST_TICKETS",
    LOAD_SIDEBAR: "LOAD_SIDEBAR",
    LIST_USER_TICKETS:"LIST_USER_TICKETS"
};
