export default {
    CHANGE: "CHANGE",
    TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR",
    LIST_PLACES: "LIST_PLACES",
    LIST_TOURS: "LIST_TOURS",
    LIST_TRIPS: "LIST_TRIPS",
    LOAD_SIDEBAR: "LOAD_SIDEBAR"
};